AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - shared_examples
  
Style/GlobalVars:
  AllowedVariables:
    - $CXXFLAGS
